site_name: mafm
site_url: https://Jianhua-Wang.github.io/mafm
repo_url: https://github.com/Jianhua-Wang/mafm
repo_name: Jianhua-Wang/mafm
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Tutorial:
    - Overview: tutorial.md
    - Getting Started: tutorial/getting-started.md
    - Quick Start: tutorial/quick-start.md
    - Single-Input Fine-Mapping: tutorial/single-input.md
    - Multi-Input Fine-Mapping: tutorial/multi-input.md
    - Web Visualization: tutorial/web-visualization.md
    - Web Example: tutorial/web-example.md
    - Advanced Topics: tutorial/advanced.md
  - Modules: api.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - admonition
  - toc:
      # baselevel: 2
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
  - def_list
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
        - https://mkdocstrings.github.io/autorefs/objects.inv
        options:
          docstring_style: numpy
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          show_submodules: yes
      # watch:
      #   - mafm
extra:
  social:
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
